{
  "pci_projects_project_network_private_create": "Utwórz prywatną sieć",
  "pci_projects_project_network_private_create_init_error": "Wystąpił błąd podczas pobierania informacji: {{message}}",
  "pci_projects_project_network_private_create_configure": "Skonfiguruj prywatną sieć",
  "pci_projects_project_network_private_create_configure_address": "Adres prywatnej sieci:",
  "pci_projects_project_network_private_create_configure_mask": "Maska:",
  "pci_projects_project_network_private_create_configure_dhcp": "Przydzielanie adresów:",
  "pci_projects_project_network_private_create_configure_dhcp_active": "Dynamiczne (DHCP)",
  "pci_projects_project_network_private_create_configure_dhcp_inactive": "Statyczne (Ręczne)",
  "pci_projects_project_network_private_create_configure_choose_vlan": "Wybierz ID sieci VLAN",
  "pci_projects_project_network_private_create_configure_vlan": "ID sieci VLAN:",
  "pci_projects_project_network_private_create_configure_vlan_limits": "Wartość między 2 a 4000",
  "pci_projects_project_network_private_create_configure_vlan_taken": "Ta sieć VLAN jest już zajęta.",
  "pci_projects_project_network_private_create_configure_api": "Możesz dostosować zakresy adresów za pomocą API.",
  "pci_projects_project_network_private_create_localisation": "Lokalizacja",
  "pci_projects_project_network_private_create_localisation_range": "Zakres",
  "pci_projects_project_network_private_create_localisation_gateway": "Włącz bramę domyślną.",
  "pci_projects_project_network_private_create_name_step": "Nadaj nazwę prywatnej sieci.",
  "pci_projects_project_network_private_create_name": "Nazwa prywatnej sieci:",
  "pci_projects_project_network_private_create_name_placeholder": "Wprowadź nazwę prywatnej sieci.",
  "pci_projects_project_network_private_create_submit": "Utwórz",
  "pci_projects_project_network_private_create_loading": "Trwa tworzenie prywatnej sieci. Może to potrwać kilka minut",
  "pci_projects_project_network_private_create_success": "Prywatna sieć została utworzona.",
  "pci_projects_project_network_private_create_error": "Wystąpił błąd podczas tworzenia prywatnej sieci: {{message}}"
}
