{
  "dedicatedCloud_datacenter_order_ip": "Nie masz dostępnych pul adresów IP. Proszę <a ui-sref=\"{{sref}}\">zamówić</a>",
  "dedicatedCloud_datacenter_drp_confirm_create_success_part_one": "Twój PRA Zerto został pomyślnie utworzony!",
  "dedicatedCloud_datacenter_drp_confirm_create_success_part_two": "Otrzymałeś swoje hasło ZSSP na adres e-mail {{email}}.",
  "dedicatedCloud_datacenter_drp_confirm_creation_pending": "Twój PRA Zerto jest w trakcie aktywacji. Operacja może zająć do 4 godzin.",
  "dedicatedCloud_datacenter_drp_confirm_creation_pending_task_EPCC": "Nie wahaj się sprawdzić zadania enableDisasterRecovery w głównym PCC, aby śledzić jego postęp.",
  "dedicatedCloud_datacenter_drp_confirm_create_error": "Wystąpił błąd podczas aktywacji twojego PRA.",
  "dedicatedCloud_datacenter_drp_confirm_summary_title": "Podsumowanie konfiguracji twojej witryny Zerto",
  "dedicatedCloud_datacenter_drp_confirm_summary_drp_type": "Typ planu odzyskiwania po awarii",
  "dedicatedCloud_datacenter_drp_confirm_summary_first_ovh_datacenter": "Główne centrum danych",
  "dedicatedCloud_datacenter_drp_confirm_summary_first_ovh_pcc_EPCC": "Główna chmura prywatna",
  "dedicatedCloud_datacenter_drp_confirm_summary_first_onPremise_datacenter": "Centrum danych OVH",
  "dedicatedCloud_datacenter_drp_confirm_summary_first_onPremise_pcc_EPCC": "Chmura prywatna OVH",
  "dedicatedCloud_datacenter_drp_confirm_summary_secondary_datacenter": "Centrum danych podrzędne",
  "dedicatedCloud_datacenter_drp_confirm_summary_secondary_pcc_EPCC": "Prywatna chmura wtórna",
  "dedicatedCloud_datacenter_drp_confirm_delete_drp_title": "Na zawsze usunąć opcję Zerto",
  "dedicatedCloud_datacenter_drp_confirm_delete_drp_action_text": "Usuń Zerto",
  "dedicatedCloud_datacenter_drp_confirm_delete_drp_modal_title": "Usunięcie opcji Zerto",
  "dedicatedCloud_datacenter_drp_confirm_delete_drp_modal_question": "Czy na pewno chcesz usunąć opcję Zerto? Ta akcja jest nieodwracalna.",
  "dedicatedCloud_datacenter_drp_confirm_delete_drp_success": "Twój plan odzyskiwania po awarii Zerto jest w trakcie usuwania. Operacja zajmie kilka minut",
  "dedicatedCloud_datacenter_drp_confirm_delete_drp_error": "Wystąpił błąd podczas usuwania planu odzyskiwania działalności",
  "dedicatedCloud_datacenter_drp_required_vpn_configuration": "Aby zakończyć aktywację swojego planu odzyskiwania po awarii Zerto, prosimy o dodanie poniższych adresów IP VPN",
  "dedicatedCloud_datacenter_drp_vpn_presharedkey": "Klucz szyfrowania VPN (PSK)",
  "dedicatedCloud_datacenter_drp_vpn_remoteEndpointPublicIp": "Publiczny adres IP zdalnego VPN",
  "dedicatedCloud_datacenter_drp_vpn_remoteEndpointInternalIp": "Prywatny adres IP zdalnego VPN",
  "dedicatedCloud_datacenter_drp_vpn_remoteZvmInternalIp": "Adres IP twojego Zvm",
  "dedicatedCloud_datacenter_drp_vpn_validate": "Potwierdź",
  "dedicatedCloud_datacenter_drp_vpn_change_parameters": "Zmień ustawienia",
  "dedicatedCloud_datacenter_drp_vpn_success": "Aktualizacja konfiguracji VPN została pomyślnie wykonana",
  "dedicatedCloud_datacenter_drp_vpn_error": "Wystąpił błąd podczas aktualizacji konfiguracji VPN",
  "dedicatedCloud_datacenter_drp_vpn_ip_invalid": "Proszę wprowadzić prawidłowy adres IPv4 (np: 192.168.0.1)",
  "dedicatedCloud_datacenter_drp_confirm_order": "Twój <a target=\"_blank\" href=\"{{billUrl}}\" rel=\"noopener\">formularz zamówienia</a> został pomyślnie wygenerowany. Po dokonaniu płatności będziesz mógł sprawdzić zadanie enableDisasterRecovery w zakładce Operacje, aby śledzić aktywację opcji.",
  "dedicatedCloud_datacenter_drp_confirm_creation_pending_task_MBM": "Nie wahaj się sprawdzić zadania enableDisasterRecovery w głównym Essentials, aby śledzić jego postęp.",
  "dedicatedCloud_datacenter_drp_confirm_summary_first_ovh_pcc_MBM": "Główny Essentials",
  "dedicatedCloud_datacenter_drp_confirm_summary_first_onPremise_pcc_MBM": "Zarządzany Bare Metal OVH",
  "dedicatedCloud_datacenter_drp_confirm_summary_secondary_pcc_MBM": "Podstawy wtórne",
  "dedicatedCloud_datacenter_drp_vpn_remoteVraNetwork": "Sieć VRA Datacenter na miejscu",
  "dedicatedCloud_datacenter_drp_vpn_ip_block_invalid": "Proszę wprowadzić prawidłowy adres IPv4Block (np: 192.168.0.1/10)"
}
